### ISSUE TITLE
remove player during captain / picking phase

### ISSUE THREAD

**Issue by hvownij** [UT2004-Coding-Projects/Hv-PugBot#11]
attached is our chat Nolja.

this would be more of a admin / mod thing
[2:55 AM]
well maybe a user thing. IDK
[2:55 AM]
but the ability to leave a pug once captains are selected
[2:55 AM]
revert back to gathering phase(edited)
[2:55 AM]
grab anyone that is already queued like it does now

tenzToday at 2:56 AM
oh ok
[2:56 AM]
so the scenario is

HvToday at 2:56 AM
if someone wants to leave during captains phase we are stuck

tenzToday at 2:57 AM
- 8/8 pug gets filled, everyone hits checkmark
- Captain A and captain B selected
- Captain A begins picking
- player F says "nvm I cant play sorry"
- the match state is fked cuz this player can't leave

HvToday at 2:57 AM
Yep
[2:57 AM]
and the only solution to fix it

tenzToday at 2:57 AM
aka all players are trapped in this Match until its finished pick phase

HvToday at 2:57 AM
is cancel match

tenzToday at 2:57 AM
or .cancel
[2:57 AM]
i see ok

HvToday at 2:57 AM
yeah
[2:57 AM]
basically the code is prolly already there
[2:58 AM]
when someone clicks abort this behavior happens currently
[2:58 AM]
but its not at the captains picking phase
[2:59 AM]
but cancel match is also a good thing to keep in if admins determine its way too stacked or something then they can cancel it

tenzToday at 3:00 AM
gotcha
[3:00 AM]
i'm trying to see where that abort is implemented
[3:00 AM]
do u already know?

HvToday at 3:00 AM
I have not looked yet

tenzToday at 3:00 AM
I have a hunch its this: https://github.com/UT2004-Coding-Projects/Hv-PugBot/blob/main/modules/bot.py#L1959

HvToday at 3:00 AM
but you either click the check box or the abort reaction

tenzToday at 3:00 AM
.reset_players

tenzToday at 3:05 AM
https://github.com/UT2004-Coding-Projects/Hv-PugBot/blob/42253a86e1c93137b05d576a51e364b2bcd945fd/modules/bot.py#L408

[3:06 AM]
this is the fn that is called when a player doesnt hit ready
[3:06 AM]
could you add the issue tmrw? just so we have it documented

HvToday at 3:08 AM
Yes I will add this issue and our chat

**Comment by tchoedak** [comment]
Solved in this PR https://github.com/UT2004-Coding-Projects/Hv-PugBot/pull/13
